{"nbformat":4,"nbformat_minor":0,"metadata":{"celltoolbar":"Slideshow","colab":{"name":"L16 Exceptions and Unit Testing.ipynb","provenance":[],"collapsed_sections":[]},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.4"}},"cells":[{"cell_type":"markdown","metadata":{"id":"L4Yq7MGPZERE"},"source":["# Lecture 16 - Exceptions and Unit Testing (https://bit.ly/2HNzGsO)\n","\n","* Unit-testing with unitest\n","* Exceptions and error handling\n"]},{"cell_type":"markdown","metadata":{"id":"iPsTLSW0BJSu"},"source":["# Unit testing with the unittest module\n","\n","* As programs grow in complexity, the scope for bugs becomes huge.\n","\n","* Satisfactorily debugging a complex program without systematic testing is **hard or even intractable**.\n","\n","* With **unit-testing** you design tests to test individual \"units\" of the code, e.g. functions and classes.\n","\n","* Unit-testing allows you to progressively debug code and build tested modules of code with less fear that nothing will work when you finally put it together."]},{"cell_type":"markdown","metadata":{"id":"KeaobT9uqS3v"},"source":["# Unittesting example: Fibonacci numbers\n","\n","* Let's look at a simple example, debugging a function for computing members of the Fibonacci sequence\n","\n","* Recall the ith Fibonacci number is equal to the sum of the previous two Fibonacci numbers, and 0 and 1 are the 0th and 1st Fibonacci numbers.\n","\n","  * i.e. fib(i) = fib(i-1) + f(i-2), for i > 1\n","\n","* This definition is naturally recursive, so we can use a recursive implementation of the function."]},{"cell_type":"code","metadata":{"id":"Fv6ucZiFYbG9"},"source":["# Example demonstrating unittesting using the Python\n","# unittest module\n","\n","# Let's suppose we want to test our implementation of the fibonnaci sequence\n","def fib(i):\n","  \"\"\" Compute the ith fibonacci number recursively\n","  \n","  Reminder the ith fibonnaci number is equal to the sum of the previous\n","  two previous fibonnacci numbers, where the 0th fibonacci number is 0 and the 1st\n","  is 1.\n","  \"\"\"\n","  assert type(i) == int and i >= 0\n","  return 1 if i == 0 else 1 if i == 1 else fib(i-1) + fib(i-2) # Note this is not quite right!\n","\n"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"zpYh0wDB5TCb"},"source":["Here's how we test it using unittest:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"nCodoVss5Jb-","executionInfo":{"elapsed":374,"status":"ok","timestamp":1608090815502,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"c7100872-7e0a-4900-a571-3b75fb9baeb7"},"source":["import unittest # unittest is the standard Python library module for unit testing,\n","# it's great\n","\n","class FibTest(unittest.TestCase): # Note the use of inheritence\n","  \"\"\" We create a test class that inherits from the unittest.TestCase\n","  class\n","  \"\"\"\n","  def test_calc_x(self):\n","    \"\"\" Each test we create must start with the name \"test\"\n","    \"\"\"\n","    self.assertEqual(fib(0), 0)\n","    self.assertEqual(fib(1), 1)\n","    self.assertEqual(fib(2), 1)\n","    self.assertEqual(fib(3), 2)\n","    self.assertEqual(fib(4), 3)\n","    self.assertEqual(fib(5), 5)\n","    self.assertEqual(fib(6), 8)\n","\n","unittest.main(argv=['first-arg-is-ignored'], exit=False)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["F\n","======================================================================\n","FAIL: test_calc_x (__main__.FibTest)\n","Each test we create must start with the name \"test\"\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-4-cf93929006b0>\", line 11, in test_calc_x\n","    self.assertEqual(fib(0), 0)\n","AssertionError: 1 != 0\n","\n","----------------------------------------------------------------------\n","Ran 1 test in 0.003s\n","\n","FAILED (failures=1)\n"],"name":"stderr"},{"output_type":"execute_result","data":{"text/plain":["<unittest.main.TestProgram at 0x7f3cbac25f60>"]},"metadata":{"tags":[]},"execution_count":4}]},{"cell_type":"markdown","metadata":{"id":"_29yYOF1rrSQ"},"source":["Okay, so our test failed, let's fix it:"]},{"cell_type":"code","metadata":{"id":"r72cNfLsrxkc"},"source":["# Example demonstrating unittesting using the Python\n","# unittest module\n","\n","# Let's suppose we want to test our implementation of the fibonnaci sequence\n","def fib(i):\n","  \"\"\" Compute the ith fibonacci number recursively\n","  \n","  Reminder the ith fibonnaci number is equal to the sum of the previous\n","  two previous fibonnacci numbers, where the 0th fibonacci number is 0 and the 1st\n","  is 1.\n","  \"\"\"\n","  assert type(i) == int and i >= 0\n","  return 0 if i == 0 else 1 if i == 1 else fib(i-1) + fib(i-2) # That's right"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"qKcD3NG_sA2z"},"source":["Now we can rerun the tests:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"8hmU0_UPr4U_","executionInfo":{"elapsed":597,"status":"ok","timestamp":1608090883841,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"b7534222-9deb-4b84-81b1-2ca0df42d248"},"source":["import unittest # unittest is the standard Python library module for unit testing,\n","# it's great\n","\n","class FibTest(unittest.TestCase): # Note the use of inheritence\n","  \"\"\" We create a test class that inherits from the unittest.TestCase\n","  class\n","  \"\"\"\n","  def test_calc_x(self):\n","    \"\"\" Each test we create must start with the name \"test\"\n","    \"\"\"\n","    self.assertEqual(fib(0), 0)\n","    self.assertEqual(fib(1), 1)\n","    self.assertEqual(fib(2), 1)\n","    self.assertEqual(fib(3), 2)\n","    self.assertEqual(fib(4), 3)\n","    self.assertEqual(fib(5), 5)\n","    self.assertEqual(fib(6), 8)\n","\n","unittest.main(argv=['first-arg-is-ignored'], exit=False)"],"execution_count":null,"outputs":[{"output_type":"stream","text":[".\n","----------------------------------------------------------------------\n","Ran 1 test in 0.001s\n","\n","OK\n"],"name":"stderr"},{"output_type":"execute_result","data":{"text/plain":["<unittest.main.TestProgram at 0x7f3cba3bb550>"]},"metadata":{"tags":[]},"execution_count":6}]},{"cell_type":"markdown","metadata":{"id":"kApqUqdysJsV"},"source":["Okay, this example is contrived, but the idea that you should write code to test your code turns out to be remarkably useful.\n","\n","What if you want to write multiple tests for multiple different functions?"]},{"cell_type":"markdown","metadata":{"id":"2PGtely3EFs8"},"source":["# Writing multiple tests: setUp() and tearDown()\n","\n","* It is good to keep tests small and modular.\n","\n","* If you want to test lots of related functions, e.g. the functions of a class, it is therefore helpful to have shared \"setup\" and \"cleanup\" functions that are run, respectively, before and after each test. You can achieve this with the *setUp()* and *tearDown()* functions of the unittest.TestCase function."]},{"cell_type":"code","metadata":{"id":"sNBmpzjsEAqh"},"source":["# Here's the card class we studied before when looking at the Old Maid card game:\n","\n","class Card:\n","  \"\"\" Represents a card from a deck of cards.\n","  \"\"\"\n","  \n","  # Here are some class variables\n","  # to represent possible suits and ranks\n","  suits = [\"Clubs\", \"Diamonds\", \"Spades\", \"Hearts\"]\n","  ranks = [\"narf\", \"Ace\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\",\n","           \"8\", \"9\", \"10\", \"Jack\", \"Queen\", \"King\"]  \n","\n","  def __init__(self, suit=0, rank=0):\n","    \"\"\" Create a card using integer variables to represent suit and rank.\n","    \"\"\"\n","    # Couple of handy asserts to check any cards we build make sense\n","    assert suit >= 0 and suit < 4  \n","    assert rank >= 0 and rank < 14\n","        \n","    self.suit = suit\n","    self.rank = rank\n","\n","  def __str__(self):\n","    # The lookup in the suits/ranks lists prints \n","    # a human readable representation of the card.\n","    return (self.ranks[self.rank] + \" of \" + self.suits[self.suit])\n","      \n","  def same_color(self, other):\n","    \"\"\" Returns the True if cards have the same color else False\n","    Diamons and hearts are both read, clubs and spades are both black.\n","    \"\"\"\n","    return self.suit == other.suit or self.suit == (other.suit + 2) % 4\n","    \n","  # The following methods implement card comparison\n","    \n","  def cmp(self, other):\n","    \"\"\" Compares the card with another, returning 1, 0, or -1 depending on \n","    if this card is greater than, equal or less than the other card, respectively.\n","      \n","    Cards are compared first by suit and then rank.\n","    \"\"\"\n","    # Check the suits\n","    if self.suit > other.suit: return 1\n","    if self.suit < other.suit: return -1\n","    # Suits are the same... check ranks\n","    if self.rank > other.rank: return 1\n","    if self.rank < other.rank: return -1\n","    # Ranks are the same... it's a tie\n","    return 0\n","      \n","  def __eq__(self, other):\n","    return self.cmp(other) == 0\n","\n","  def __le__(self, other):\n","    return self.cmp(other) <= 0\n","\n","  def __ge__(self, other):\n","    return self.cmp(other) >= 0\n","\n","  def __gt__(self, other):\n","    return self.cmp(other) > 0\n","\n","  def __lt__(self, other):\n","    return self.cmp(other) < 0\n","\n","  def __ne__(self, other):\n","    return self.cmp(other) != 0"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Wg9_BufJbXyn"},"source":["To test the individual functions we could do something like this:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"WhXVuy3Tbefl","executionInfo":{"elapsed":375,"status":"ok","timestamp":1608091284365,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"0a1cb74f-a999-4699-fb86-90a284ae2779"},"source":["class CardTest(unittest.TestCase):\n","  \"\"\" Test the Card class\n","  \"\"\"\n","  \n","  def setUp(self):\n","    print(\"setUp\")\n","    # This function gets run before each test\n","    self.aceClubs = Card(0, 1) # Ace of clubs\n","    self.aceDiamonds = Card(1, 1) # Ace of diamonds\n","    self.aceSpades = Card(2, 1) # Ace of spades\n","    \n","  def tearDown(self):\n","    # This function gets run after each function. \n","    # Here I do nothing in teardown, but print a message\n","    # but you can use it to cleanup temporary files, etc.\n","    print(\"tearDown\")\n","  \n","  def test_same_color(self):\n","    \"\"\" Tests Card.same_color()\n","    \"\"\"\n","    print(\"Running test_same_color\") # These print messages are just to show you what's going on\n","    self.assertTrue(self.aceClubs.same_color(self.aceSpades))\n","    self.assertFalse(self.aceSpades.same_color(self.aceDiamonds))\n"," \n","  def test_str(self):\n","    \"\"\" Tests Card.__str__()\"\"\"\n","    print(\"Running test_str\")\n","    self.assertEqual(str(self.aceClubs), \"Ace of Clubs\")\n","    self.assertEqual(str(self.aceSpades), \"Ace of Spades\")\n","    self.assertEqual(str(self.aceDiamonds), \"Ace of Diamonds\")\n","\n","unittest.main(argv=['first-arg-is-ignored'], exit=False)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["..."],"name":"stderr"},{"output_type":"stream","text":["setUp\n","Running test_same_color\n","tearDown\n","setUp\n","Running test_str\n","tearDown\n"],"name":"stdout"},{"output_type":"stream","text":["\n","----------------------------------------------------------------------\n","Ran 3 tests in 0.010s\n","\n","OK\n"],"name":"stderr"},{"output_type":"execute_result","data":{"text/plain":["<unittest.main.TestProgram at 0x7f3cba3d3ef0>"]},"metadata":{"tags":[]},"execution_count":8}]},{"cell_type":"markdown","metadata":{"id":"XZyCu9gYtsSa"},"source":["# Writing Test Suites\n","\n","* Generally for each Python module you write you create an accompanying unittest module.\n","  * e.g. if you write \"foo.py\" you also create \"fooTest.py\". \n","\n","* It's beyond scope here, but as you write more complex programs, with multiple modules organized into packages, you can automate running all your tests together in one test suite. When you make a change to your code you then rerun all the tests and check everything is still good.\n","\n","* As a rough rule of thumb, good programmers write about us much unit test code as they write program code.\n","  * It seems like a long way around, but it is generally quicker and more manageable than ad hoc debugging which is otherwise inevitable. \n","\n","* One popular approach is to write the tests before writing the core of the program, this is partly the philosophy of \"test driven development\"\n","  * This helps figure out what the program should do and how it should behave before going to far into the actual implementation."]},{"cell_type":"markdown","metadata":{"id":"WEmfPnG2EUg8"},"source":["# Exceptions\n","\n","When a runtime error occurs Python creates an exception. We've seen these, e.g.:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":186},"id":"7Glnk2WEEWYL","executionInfo":{"elapsed":486,"status":"error","timestamp":1574381127895,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AAuE7mBMnWy8dDR7jyTHNy9tPaRx6DCyA3QKrIcuQ7R4=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"2a09fd28-4d35-4420-ebae-e09c3acee49b"},"source":["assert False # Creates an AssertionError, a kind of exception"],"execution_count":null,"outputs":[{"output_type":"error","ename":"AssertionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)","\u001b[0;32m<ipython-input-12-a50d55fde793>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32massert\u001b[0m \u001b[0;32mFalse\u001b[0m \u001b[0;31m# Creates an AssertionError, a kind of exception\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mAssertionError\u001b[0m: "]}]},{"cell_type":"markdown","metadata":{"id":"ur1rkvM_hD0I"},"source":["* So far we've just encountered exceptions when the program fails, but actually we can frequently handle exceptions within the program and not crash. \n","\n","* To do this we use the try / except syntax.\n","\n","* Consider:\n"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"dzu99TMohQcm","executionInfo":{"elapsed":435,"status":"ok","timestamp":1608092288544,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"3d548d56-013e-46f7-8003-9a3339ffc47d"},"source":["try: \n","  assert False\n","except AssertionError:\n","  print(\"We got an assert error\")\n","  \n","print(\"But we're fine!\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["We got an assert error\n","But we're fine!\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"jWpzzBljxRtd"},"source":["# The syntax is \n","\n","try: \n","  STATEMENT_BLOCK_1\n","except [ERROR TYPE]:\n","  STATEMENT_BLOCK_2"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"gLs88wCrijJy"},"source":["The way this works:\n","\n"," * The statement block STATEMENT_BLOCK_1 is executed.\n"," * If an exception occurs of type ERROR_TYPE during the execution of STATEMENT_BLOCK_1 then STATEMENT_BLOCK_1 stops execution and STATEMENT_BLOCK_2 executes. \n"," * If not exception occurs during STATEMENT_BLOCK_1, STATEMENT_BLOCK_2 is skipped.\n"," * This allows us to handle unexpected events in a predictable way"]},{"cell_type":"markdown","metadata":{"id":"6bpXcrjQxtN4"},"source":["Consider how parsing user input can create errors:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":183},"id":"8SZ9lCn0gjRF","executionInfo":{"elapsed":5502,"status":"error","timestamp":1608092348364,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"04f35f03-9dd3-4534-9f90-7992edab81f2"},"source":["i = int(input(\"Enter an integer: \")) # What happens if I don't enter a valid integer?"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Enter an integer: foo\n"],"name":"stdout"},{"output_type":"error","ename":"ValueError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-11-31b04b94ed4b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mi\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Enter an integer: \"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;31m# What happens if I don't enter a valid integer?\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'foo'"]}]},{"cell_type":"markdown","metadata":{"id":"AEH6i4Yghv5s"},"source":["We can handle this using try/except:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"09rznfdSg7tv","executionInfo":{"elapsed":5011,"status":"ok","timestamp":1608092389137,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"289879e3-aece-48d5-d374-9f65d6fa20ba"},"source":["while True:\n","  try:\n","    i = int(input(\"Enter an integer: \"))\n","    break\n","  except ValueError: \n","    print(\"Got an error parsing user input, try again!\")\n","    \n","print(\"You entered: \", i)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Enter an integer: foo\n","Got an error parsing user input, try again!\n","Enter an integer: 10\n","You entered:  10\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"ocTPd5poixNz"},"source":["**You don't have to specify the exception type** \n","\n","* If you don't know what error to anticipate you can not specify the type of exception:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":52},"id":"dMg1FKaJi8vI","executionInfo":{"elapsed":4740,"status":"ok","timestamp":1574381810504,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AAuE7mBMnWy8dDR7jyTHNy9tPaRx6DCyA3QKrIcuQ7R4=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"0650ef72-c4e2-41a4-fcbe-df572cefcb82"},"source":["while True:\n","  try:\n","    i = int(input(\"Enter an integer: \"))\n","    break\n","  except: # Note we don't say what kind of error it is\n","    print(\"Got an error parsing user input, try again!\")\n","\n","print(\"You entered: \", i)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Enter an integer: 1\n","You entered:  1\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"hjvNDiCcjosT"},"source":["The downside of not specifying the type of the expected exception, is that  except without a type will catch all exceptions, possibly including unrelated errors.\n"]},{"cell_type":"markdown","metadata":{"id":"bHqpCuKmkI4e"},"source":["# Finally \n","\n","Finally allows us to specify code that will be run regardless of if there is an error:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ITFjFenBlSUQ","executionInfo":{"elapsed":358,"status":"ok","timestamp":1608092491019,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"f9e63e8e-3c74-48a4-e97c-4377e864d924"},"source":["try:\n","  f = open(\"out.txt\", \"w\")\n","  f.write(\"Hello, file!\\n\")\n","  assert 1 == 2\n","except:\n","  print(\"Got an error\")\n","finally:\n","  print(\"Closing the file\")\n","  f.close()"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Got an error\n","Closing the file\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"HaHUZWhsm90X"},"source":["The way this works: \n","\n","* if there is an error, the error is dealt with.\n","\n","* the finally clause is then run, regardless of if there is an error or not\n"," "]},{"cell_type":"markdown","metadata":{"id":"AwL6DdxaoQJd"},"source":["# Raise\n","\n","If you want to create your own exception use \"Raise\":"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":338},"id":"CXwrlHwopfeo","executionInfo":{"elapsed":3630,"status":"error","timestamp":1608092534622,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"0482cf6b-bda6-4de9-89f8-22efec05883a"},"source":["def get_age():\n","  age = int(input(\"Please enter your age: \"))\n","  if age < 0:\n","    # Create a new instance of an exception\n","    my_error = ValueError(\"{0} is not a valid age\".format(age))\n","    raise my_error\n","  return age\n","\n","get_age()\n"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Please enter your age: -5\n"],"name":"stdout"},{"output_type":"error","ename":"ValueError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-14-7c4ae1e347c8>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      7\u001b[0m   \u001b[0;32mreturn\u001b[0m \u001b[0mage\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 9\u001b[0;31m \u001b[0mget_age\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-14-7c4ae1e347c8>\u001b[0m in \u001b[0;36mget_age\u001b[0;34m()\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0;31m# Create a new instance of an exception\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0mmy_error\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"{0} is not a valid age\"\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mage\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m     \u001b[0;32mraise\u001b[0m \u001b[0mmy_error\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m   \u001b[0;32mreturn\u001b[0m \u001b[0mage\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: -5 is not a valid age"]}]},{"cell_type":"markdown","metadata":{"id":"P5pblXmQp48w"},"source":["You can also use this to \"rethrow\" an exception:"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":252},"id":"C8UvvAwVp9xO","executionInfo":{"elapsed":360,"status":"error","timestamp":1608092557060,"user":{"displayName":"Benedict Paten","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gh2rYrrH6yoNnUp0Oj4p4ouybc6ZcWGyPmKFtIY=s64","userId":"06399644931392855882"},"user_tz":480},"outputId":"24d06d86-89d2-4824-9270-bdd2f6223447"},"source":["try: # This is a contrived example\n","  assert 1 == 2\n","except:\n","  print(\"Got an error\")\n","  raise # This \"rethrows\" the exception we caught\n","\n","  "],"execution_count":null,"outputs":[{"output_type":"stream","text":["Got an error\n"],"name":"stdout"},{"output_type":"error","ename":"AssertionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)","\u001b[0;32m<ipython-input-15-741a0e2b18be>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;31m# This is a contrived example\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m   \u001b[0;32massert\u001b[0m \u001b[0;36m1\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;32mexcept\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m   \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Got an error\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m   \u001b[0;32mraise\u001b[0m \u001b[0;31m# This \"rethrows\" the exception we caught\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mAssertionError\u001b[0m: "]}]},{"cell_type":"markdown","metadata":{"id":"nlJtaCzbQg7I"},"source":["Note: There is a lot more to say about exceptions and writing false tolerant code, but hopefully this summary is a good start!"]},{"cell_type":"markdown","metadata":{"id":"H9KZX9qqyXK4"},"source":["# Challenge"]},{"cell_type":"code","metadata":{"id":"qZ41OaQ6rvRJ"},"source":["# Practice problem\n","\n","# Write a function \"get_file\" to ask the user for a file name.\n","# Return an open file handle to the users file in \"read\" mode.\n","# Use exception handling to deal with the case that the user's file\n","# does not exist, printing an error saying \"File does not exist, try again\" \n","# and trying again\n","\n","\n","\n","f = get_file()\n","f.close()"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"PucGp8tOZC_s"},"source":["# Reading\n","\n","* Open book Chapter 19: (exceptions)\n","http://openbookproject.net/thinkcs/python/english3e/exceptions.html\n","\n","# Homework\n","\n","* Zybooks Reading 16\n"]}]}